### PR TITLE
Fix a typo in the readme

### PR DESCRIPTION
**Pull request by zeke**
s/let's/lets/

:wave:

### CODE REVIEW

**Comment by zeke** [comment]
cc @ryanbrainard. Do you live in Korea now?

**Comment by ryanbrainard** [comment]
Not yet, but I will be soon. Will be there for a couple years.

**Comment by zeke** [comment]
multilingual children ftw!

**Comment by ryanbrainard** [comment]
Yep, that's the idea :)

**Comment by zeke** [comment]
👻

**Pull request closed without merging**
